# This manifest bootstraps a k8s cluster with services that should alwasy be
# installed, regardless of whether running on a cloud provider or locally. First
# it installs tiller, then installs cert-manager then nginx ingress. Because
# kapps must be installed in exactly that order, parallelism is disabled for
# this manifest.
#
# This manifest could be a good place to put other universal, cluster-wide
# kapps, e.g. for pod security policies, RBAC, etc.

# Kapps listed under this key will be installed if they are not currently
# installed in the target cluster.
options:
  parallelisation: 1      # kapps in this manifest must be installed in order,
                          # so disable parallelism for this manifest
present:
  tiller:
    sources:
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      #      branch: tiller-0.1.0
      path: incubator/tiller
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      path: incubator/common-makefiles

  # The default installer for manifests is stored in config so we don't need
  # to add it to every entry. But we could in future with e.g. `installer: my-installer`

  # The simplest manifest entry uses defaults for e.g. the helm namespace,
  # chart name, etc. when using `helm` as the installer.
  cert-manager:       # Globally-unique identifier. For helm this corresponds
    # to the release name. If that's too restrictive we could
    # generate a globally-unique identifier based on the
    # manifest, but for now we'll keep it simple.
    # todo - make the above manifest-unique and be the kapp name. Make the
    # kapp ID be "<manifest_id>-<kapp_id>" and allow kapp IDs to be explicitly overridden..
    # Make the kapp ID be the helm release name.

    # Sources to checkout as siblings in the cache for this kapp. This allows
    # creating a cache entry from e.g. the actual kapp source, a directory of
    # shared makefiles, and/or pulling in `values.yaml` files etc. from a
    # separately versioned source.
    sources:
    # sources are downloaded by `acquirers`. Currently we only have a git
    # acquirer, and the acquirer to use is inferred from the uri. Other
    # settings are specific to the acquirer.
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      # branch: cert-manager-0.1.0
      path: incubator/cert-manager
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      path: incubator/common-makefiles

  # The default installer for manifests is stored in config so we don't need
  # to add it to every entry. But we could in future with e.g. `installer: my-installer`
  ingress:      # this can be anything - it doesn't need to relate to the name of any source
    sources:
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      #branch: nginx-ingress-0.1.0
      path: incubator/nginx-ingress
      name: ingress-kapp      # defaults to the basename of the given path, but can be explicitly defined
    - uri: git@github.com:sugarkube/kapps.git
      branch: master
      path: incubator/common-makefiles
      includeValues: false   # Defaults to true. There aren't any helm/terraform values here,
        # but if there were this would mean they aren't passed to the
        # kapp when it's being installed. This allows you to keep your
        # values in a separate repo to the actual kapp if you want (for
        # helm/terraform kapps).
